// <auto-generated />

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using QuestApp.Data;
using System;

namespace QuestApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20180326205237_Add_Enum")]
    partial class Add_Enum
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("QuestApp.Models.Booking", b =>
                {
                    b.Property<int>("BookingId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("BookedDate");

                    b.Property<string>("Email");

                    b.Property<bool>("IsDeleted");

                    b.Property<int>("Mobile");

                    b.Property<string>("Name");

                    b.Property<string>("Note");

                    b.Property<int>("TimeSlotId");

                    b.Property<int>("TreatmentId");

                    b.HasKey("BookingId");

                    b.HasIndex("TimeSlotId");

                    b.HasIndex("TreatmentId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("QuestApp.Models.LU_TimeSlot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("TimeSlotTitle");

                    b.HasKey("Id");

                    b.ToTable("LU_TimeSlot");
                });

            modelBuilder.Entity("QuestApp.Models.LU_Treatment", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("TreatmentDescription");

                    b.Property<int>("TreatmentTitle");

                    b.HasKey("id");

                    b.ToTable("Treatments");
                });

            modelBuilder.Entity("QuestApp.Models.Booking", b =>
                {
                    b.HasOne("QuestApp.Models.LU_TimeSlot", "TimeSlot")
                        .WithMany("Bookings")
                        .HasForeignKey("TimeSlotId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("QuestApp.Models.LU_Treatment", "Treatment")
                        .WithMany("Bookings")
                        .HasForeignKey("TreatmentId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
